<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Storage;

/**
 * StorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getValue($name = '', $default = '')
    {
        $record = $this
            ->createQueryBuilder('s')
            ->andWhere('s.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
        if (!$record) {
            return $default;
        }
        return $record->getValue();
    }

    public function setValue($name = '', $value = '')
    {
        $record = $this
            ->createQueryBuilder('s')
            ->andWhere('s.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
        if (!$record) {
            $record = new Storage($name, $value);
            $this->getEntityManager()->persist($record);
        }
        $record->setValue($value);
        $this->getEntityManager()->flush();
        return $value;
    }
}
