<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function paginate($offset = 0, $perPage, &$total)
    {
        
        $total = $this->createQueryBuilder("u")
            ->select('count(u)')
            ->getQuery()
            ->getSingleScalarResult();

        return $this->createQueryBuilder("u")
            ->setMaxResults($perPage)
            ->setFirstResult($offset)
            ->getQuery()
            ->getResult();
    }
}
