services:
    app.security.token_authenticator:
        class: AppBundle\Security\ApiTokenAuthenticator

    app.security.chan_user.provider:
        class: AppBundle\Security\DeviceProvider
        arguments: ['@doctrine']

    app.security.device.checker:
        class: AppBundle\Security\DeviceUserChecker
